### ISSUE TITLE
updated fused_flow to incorporate basic_aep structure and vice versa

### ISSUE THREAD

**Issue by dykesk** [FUSED-Wind/fusedwind#32]
cross check basic_aep setup with fused_wind to transfer base class material into plant_flow from basic_aep

**Comment by piredtu** [comment]
Hi Katherine,
I can see you are defining a wind turbine within the `aep_weibull_assembly` in basic_aep.py. It would be more consistent if you were using the class GenericWindTurbinePowerCurveVT in vt.py.
I can see that some code in the `WeibullWindRose` component in comp.py is equivalent to some of your code in `WeibullCDF`. I like that your component calculate the derivatives, but I'm unsure if it's worth the trouble now to change my component to include the `WeibullCDF` in it. 
Well, I have some performance issues with this part of the code, so it might be the best idea to do it anyway. I can see you are using a trapz instead of a quad for the integration. Yours is probably much faster. 
If you don't mind, I close this issue, and add a new one concerning `WeibullWindRose`
